version: '3.13'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: sqlite:///app/todo.db  # SQLite file path inside the container
    volumes:
      - .:/app  # Mounts the current directory to /app in the container